[build-system]
requires = ["setuptools>=44.0.0"]
build-backend = "setuptools.build_meta"


[[tool.mypy.overrides]]
module = [
    "scipy.*",
    "zmq",
]
ignore_missing_imports = true


[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
