[doxygen]
exclude_patterns = ["json.hpp"]

[intersphinx.mapping]
pam_documentation = "https://intelligent-soft-robots.github.io/pam_documentation"

# [mainpage]
# title = "Custom Title"
# auto_general_docs = false
